on: [push, pull_request]
name: Build
jobs:
  build:
    name: build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          echo "GO111MODULE=on" >> $GITHUB_ENV
          GOOS=windows GOARCH=amd64 go build cmd/awsssotool/ -o bin/awsssotool-windows-amd64.exe
          GOOS=linux   GOARCH=amd64 go build cmd/awsssotool/ -o bin/awsssotool-linux-amd64
          GOOS=darwin  GOARCH=amd64 go build cmd/awsssotool/ -o bin/awsssotool-darwin-amd64
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin/